// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oddfdtkpmgxpxdgieoqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZGZkdGtwbWd4cHhkZ2llb3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODE0NDEsImV4cCI6MjA3MjY1NzQ0MX0.U7g2auvRkh73ksXiT9lK086hy5D44lfzGLIJorPAOaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});